disabled_rules:
  - trailing_whitespace
  - line_length
opt_in_rules:
  - empty_count
  - force_unwrapping
  - private_outlet
included:
  - Sources
excluded:
  - Tests
  - .build
analyzer_rules:
  - unused_declaration
  - unused_import
line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true
reporter: "xcode" 