name: NookuApp
options:
  bundleIdPrefix: com.nooku
  deploymentTarget:
    iOS: 15.0
    macOS: 12.0
packages:
  Nooku:
    path: ..
targets:
  NookuApp:
    type: application
    platform: iOS
    sources:
      - NookuApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nooku.app
        INFOPLIST_FILE: NookuApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: # Your team ID here
    dependencies:
      - package: Nooku 