name: NookuApp
options:
  bundleIdPrefix: com.nooku
  deploymentTarget:
    iOS: 15.0
packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    from: 5.8.1
  CryptoSwift:
    url: https://github.com/krzyzanowskim/CryptoSwift.git
    from: 1.7.0
  SwiftSSHClient:
    url: https://github.com/gaetanzanella/swift-ssh-client.git
    from: 0.1.4
targets:
  NookuApp:
    type: application
    platform: iOS
    sources: 
      - path: NookuApp
        excludes:
          - "*.xcodeproj"
          - "*.xcworkspace"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nooku.app
        INFOPLIST_FILE: NookuApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: # Your team ID here
        TARGETED_DEVICE_FAMILY: 1,2
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
    dependencies:
      - package: Alamofire
      - package: CryptoSwift
      - package: SwiftSSHClient
        product: SSHClient 